import keyMirror from 'keymirror';

export default keyMirror({
	REQUEST_TRANSACTIONS_SUCCESS: null,

	REQUEST_CATEGORIES_SUCCESS: null, 
	REQUEST_CATEGORY_SUCCESS: null,
	UPDATE_CATEGORY_SUCCESS: null,

	REQUEST_PRODUCTS_SUCCESS: null,
	REQUEST_PRODUCT_SUCCESS: null,
	CREATE_PRODUCT_SUCCESS: null,
	UPDATE_PRODUCT_SUCCESS: null,
	
	CREATE_SESSION_SUCCESS: null,	
	REMOVE_SESSION_SUCCESS: null,

	CREATE_USER_SUCCESS: null,
	REQUEST_USER_SUCCESS: null,
	REQUEST_USERS_SUCCESS: null,

	REQUEST_INVENTORIES_SUCCESS: null,

	ERROR_UNAUTHORIZED: null,
});
